reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy]
  resources :posts, except: [:index]
end

reddit_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reddit_clone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, presence: true

  has_many :post_subs

  has_many :subs,
    through: :post_subs,
    source: :sub

  belongs_to :author,
    foreign_key: :author_id,
    class_name: :User

end

reddit_clone/app/models/post_sub.rb
# == Schema Information
#
# Table name: post_subs
#
#  id         :bigint           not null, primary key
#  sub_id     :integer          not null
#  post_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostSub < ApplicationRecord

  belongs_to :sub
  
  belongs_to :post

end

reddit_clone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint           not null, primary key
#  title        :string           not null
#  description  :text             not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord  
  validates :title, :description, presence: true

  has_many :post_subs

  has_many :posts,
    through: :post_subs,
    source: :post

  belongs_to :moderator,
    foreign_key: :moderator_id,
    class_name: :User
end

reddit_clone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord

  validates :username, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password

  after_initialize :ensure_session_token

  has_many :subs,
    foreign_key: :moderator_id,
    class_name: :Sub

  has_many :posts,
    foreign_key: :author_id,
    class_name: :Post

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user && user.is_password?(password)
    user
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

end

reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  #CELLL
  def not_logged_in?
    !logged_in?
    redirect_to subs_url
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def ensure_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def log_in(user)
    session[:session_token] = user.reset_session_token!
  end

  def logged_in?
    !!current_user
  end

  def log_out
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
  end
end

reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :ensure_logged_in

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.author_id == current_user.id && @post.update(post_params)
      redirect_to post_url(@post)
    else  
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end

  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    if @post
      @post.destroy
      redirect_to post_url(@post)
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end

end

reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :not_logged_in?
  
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      log_in(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = ["Invalid username or password"]
      render :new
    end
  end

  def destroy
    log_out
    redirect_to new_session_url
  end

end

reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  
  before_action :ensure_logged_in

  def index
    @subs = Sub.all
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.moderator_id == current_user.id && @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def show
    @sub = Sub.find(params[:id])
  end

  
  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

end

reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :not_logged_in?

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:username, :password)
  end 

end

reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if logged_in? %>
    <p>Hi, <%= current_user.username %></p>
        <form action="<%= session_url %>" method="post">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <input type="hidden" name="_method" value="delete">
          <input type="submit" value="Sign Out">
        </form>

    <% else %>
        <a href="<%= new_user_url %>">Sign Up</a>
        <a href="<%= new_session_url %>">Sign In</a>
    <% end %>


    <%= yield %>
  </body>
</html>

reddit_clone/app/views/posts/new.html.erb
<h1>Create Post</h1>


<form action="<%= posts_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>
    Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>

  <label>
   URL
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>

  <label>
   Content
    <input type="text" name="post[content]" value="<%= @post.content %>">
  </label>
  <br>
  <br>

  <label>Subs
    <% Sub.all.each do |sub| %>
    <label><%= sub.title %>
      <input type="checkbox" 
      name="post[sub_ids][]" 
      value="<%= sub.id %>">
    </label>
    <% end %>
  </label>
  <br>
  <input type="submit" value="Create Post">
</form>

reddit_clone/app/views/posts/show.html.erb
<h1>Posts Show</h1>

reddit_clone/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<form action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="patch">

  <label>
    Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>

  <label>
   Description
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label>

  <input type="submit" value="Edit Sub">
</form>

reddit_clone/app/views/subs/index.html.erb
<h1>Subs Index</h1>

<a href="<%= new_sub_url %>">Create New Sub</a>
<ul>
  <% @subs.each do |sub| %>
    <li>
      <%= sub.title %> |
      <%= sub.description %> | 
      <a href="<%= sub_url(sub) %>">View Sub</a> |
      <a href="<%= edit_sub_url(sub) %>">Edit Sub</a>
    </li>
  <% end %>
</ul>

reddit_clone/app/views/subs/new.html.erb
<h1>Create New Sub</h1>

<form action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>
    Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>

  <label>
   Description
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label>

  <input type="submit" value="Create Sub">
</form>

reddit_clone/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<p><strong>Description:</strong> <%= @sub.description %></p>

<a href="<%= edit_sub_url(@sub) %>">Edit Sub</a>

<a href="<%= subs_url %>">View All Subs</a>
<ul>
  <% @sub.posts.each do |post| %>
    <li>
    <%= post.title %> <br>
    <%= post.url %> <br>
    <%= post.content %>
    <hr>
    </li>
  <% end %>
</ul>

<a href="<%= new_post_url %>">Create Post For This Sub</a>

reddit_clone/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>
    Username
    <input type="text" name="user[username]" value="">
  </label>

  <label>
   Password
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" value="Sign Up">
</form>